version: "3"
services:
  hapi-fhir-jpa:
    image: arkhn/jpaltime:latest
    build: .
    restart: on-failure
    volumes:
      - ./application.override.yml:/opt/hapi/application.yaml
    environment:
      SPRING_CONFIG_LOCATION: file:///opt/hapi/application.yaml
      JDK_JAVA_OPTIONS: -Xmx4g

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=deadbeefdeadbeef
      - POSTGRES_DB=test-hapi-db
    ports:
      - 5432:5432
    volumes:
      - hapi-pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  hapi-pgdata:
